development:
  clients:
    default:
      uri: ENV['MONGODB_URI']
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: eurovision_picker_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
